### ISSUE TITLE
fetch_trained_model not working in latest release

### ISSUE THREAD

**Issue by mcraig-ibme** [garciadias/Neuroharmony#5]
It looks like fetch_trained_model downloads a pickled object from an earlier release that lacks the model_strategy attribute, so if you try to use this file it no longer works:
```
from neuroharmony import Neuroharmony, fetch_trained_model

import pandas as pd

data = pd.read_csv("sample_data.csv")
nh = fetch_trained_model()
nh.transform(data)

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    nh.transform(data)
  File "/home/martin/miniconda3/envs/nh/lib/python3.7/site-packages/neuroharmony/models/harmonization.py", line 458, in transform
    return self.predict(df.copy())
  File "/home/martin/miniconda3/envs/nh/lib/python3.7/site-packages/neuroharmony/models/harmonization.py", line 423, in predict
    if self.model_strategy not in ["full", "single"]:
AttributeError: 'Neuroharmony' object has no attribute 'model_strategy'
```

**Comment by garciadias** [comment]
Yes, sorry @mcraig-ibme. Unfortunately, I have left this project and can't have access to the training data anymore. I was in the middle of some changes which have broken the backwards compatibility with that trained model.

I would recommend using this code as an inspiration for you to write your own model and train it.
